In [2]:
df_final=  pd.read_csv("DataSet_LOFT.csv", sep=";")
df_final

,Unnamed: 0,id,unitId,price,rentalPrice,complexFee,area,status,currentPhase,amenities,...,objectID,_highlightResult,previousPrice,priceUpdatedAt,isOnSale,floorplan,details,condominiumDoorkeeperAvailability,propertyTax,unitFeatures
0,0,zywhpi,892813,1390000.0,NaN,1420.0,100,FOR_SALE,NaN,"['grill', 'gourmet', 'green_area', 'sports_cou...",...,zywhpi,"{'id': {'value': 'zywhpi', 'matchLevel': 'none...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,zyawv5,219643,899000.0,NaN,499.0,98,FOR_SALE,NaN,[],...,zyawv5,"{'id': {'value': 'zyawv5', 'matchLevel': 'none...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,zqp4uf,5852038,667800.0,NaN,540.0,32,FOR_SALE,NaN,"['green_area', 'gourmet', 'party_room']",...,zqp4uf,"{'id': {'value': 'zqp4uf', 'matchLevel': 'none...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,znpmoh,5873851,2491000.0,NaN,1000.0,124,FOR_SALE,NaN,"['gym', 'green_area', 'kids', 'grill', 'gourme...",...,znpmoh,"{'id': {'value': 'znpmoh', 'matchLevel': 'none...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,zm7x63,3819045,800000.0,NaN,1235.0,111,FOR_SALE,NaN,['green_area'],...,zm7x63,"{'id': {'value': 'zm7x63', 'matchLevel': 'none...",855000.0,2022-10-05T15:02:22.631Z,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5156,3835,uwg5ic,3851517,225000.0,NaN,500.0,44,FOR_SALE,NaN,"['pool', 'sports_court', 'grill']",...,uwg5ic,"{'id': {'value': 'uwg5ic', 'matchLevel': 'none...",NaN,NaN,NaN,NaN,NaN,ALL_DAY,0.08,NaN
5157,3836,uwcfbq,1447917,318000.0,NaN,300.0,51,FOR_SALE,ready_to_move,"['gym', 'gourmet', 'heated_pool']",...,uwcfbq,"{'id': {'value': 'uwcfbq', 'matchLevel': 'none...",NaN,NaN,NaN,NaN,NaN,ALL_DAY,21.06,NaN
5158,3837,uwah79,5849564,197000.0,NaN,100.0,28,FOR_SALE,NaN,[],...,uwah79,"{'id': {'value': 'uwah79', 'matchLevel': 'none...",NaN,NaN,NaN,NaN,NaN,NOT_APPLICABLE,0.08,[]
5159,3838,uw992o,939794,610000.0,NaN,619.0,67,FOR_SALE,NaN,"['gym', 'kids', 'playground', 'sports_court', ...",...,uw992o,"{'id': {'value': 'uw992o', 'matchLevel': 'none...",NaN,NaN,NaN,NaN,NaN,ALL_DAY,150.00,['SERVICE_AREA']
5160,3839,uw7kao,2893226,1280000.0,NaN,950.0,96,FOR_SALE,NaN,"['grill', 'gym', 'green_area', 'kids', 'gourme...",...,uw7kao,"{'id': {'value': 'uw7kao', 'matchLevel': 'none...",1400000.0,2022-12-07T16:11:06.636Z,NaN,NaN,NaN,ALL_DAY,333.33,"['SERVICE_AREA', 'BARBECUE_GRILL', 'TERRACE', ..."

In [3]:
sig= {
    "id" : "Id do registro", 
    "unitId" : "Id da unidade", 
    "price" : "Preço de venda do imóvel (R$)",  
    "rentalPrice" : "Preço de aluguel",  
    "complexFee" : "Taxa Condomínio" , 
    "area" : "Área do imóvel (m²)", 
    "status" : "Status do imóvel", 
    "currentPhase" : "Fase atual ", 
    "amenities" : "Comodidades do imóvel" , 
    "unitHasBalcony" : "Unidade tem varanda" , 
    "floor" : "Andar do imóvel",
    "bedrooms" : "Quantidade de quartos",
    "suits" : "Quantidade de suits",
    "image" : "Imagem do imóvel",
    "image_thumbnail" : "Miniatura da imagem do imóvel",
    "image_icon" : "Imagem de ícone do imóvel",
    "isMarketplace" : "Se é mercado",
    "productType" : "Tipo de produto",
    "contractType" : "Tipo do contrato",
    "parkingSpots" : "Quantidade de vagas",
    "createdAt" : "Data de Criação",
    "subwayShortestDistance" : "Distância mais curta do metrô (m)",
    "restrooms" : "Quantidade de banheiros",
    "propertyType" : "Tipo de propriedade",
    "hasVirtualTour" : "Tem Tuor Virtual",
    "address" : "Endereço do imóvel",
    "_geoloc" : "Geolocalização, latitude e longitude",
    "createdAtTimeStamp" : "Horário de criação",
    "imageScored" : "Imagem mais Acessada",
    "photos" : "Lista de fotos",
    "homeType" : "Tipo de imóvel",
    "objectID" : "Id do imóvel",
    "_highlightResult" : "Destacar em resultado de pesquisa",
    "previousPrice" : "Preço anterior",
    "priceUpdatedAt" : "Data de Atualização do Preço",
    "isOnSale" : "Está à venda",
    "floorplan" : "Foto da planta",
    "details" : "Detalhes",
    "isRentable" : "É rentável?",
    "condominiumDoorkeeperAvailability" : "Tem porteiro na portaria"
    }

In [4]:
list(df_final.columns)

data = dict()

data["Atributo"] = list(df_final.columns)
data["Descrição"] = [sig[column] if column in sig.keys() else " " for column in df_final.columns]
data["Tipo"] = [str(df_final[column].dtype) if column in sig.keys() else " " for column in df_final.columns]

df_info = pd.DataFrame(data)
df_info.head(40)

                  Atributo                             Descrição     Tipo
0               Unnamed: 0
1                       id                        Id do registro   object
2                   unitId                         Id da unidade    int64
3                    price         Preço de venda do imóvel (R$)  float64
4              rentalPrice                      Preço de aluguel  float64
5               complexFee                       Taxa Condomínio  float64
6                     area                   Área do imóvel (m²)    int64
7                   status                      Status do imóvel   object
8             currentPhase                           Fase atual    object
9                amenities                 Comodidades do imóvel   object
10          unitHasBalcony                   Unidade tem varanda     bool
11                   floor                       Andar do imóvel  float64
12                bedrooms                 Quantidade de quartos    int64
13                   suits                   Quantidade de suits    int64
14                   image                      Imagem do imóvel   object
15         image_thumbnail         Miniatura da imagem do imóvel   object
16              image_icon             Imagem de ícone do imóvel   object
17           isMarketplace                          Se é mercado     bool
18              isRentable                           É rentável?     bool
19             productType                       Tipo de produto   object
20            contractType                      Tipo do contrato   object
21            parkingSpots                   Quantidade de vagas    int64
22               createdAt                       Data de Criação   object
23  subwayShortestDistance     Distância mais curta do metrô (m)  float64
24               restrooms               Quantidade de banheiros    int64
25            propertyType                   Tipo de propriedade   object
26          hasVirtualTour                      Tem Tuor Virtual     bool
27                 address                    Endereço do imóvel   object
28                 _geoloc  Geolocalização, latitude e longitude   object
29      createdAtTimeStamp                    Horário de criação    int64
30             imageScored                  Imagem mais Acessada   object
31                  photos                        Lista de fotos   object
32                homeType                        Tipo de imóvel   object
33                objectID                          Id do imóvel   object
34        _highlightResult     Destacar em resultado de pesquisa   object
35           previousPrice                        Preço anterior  float64
36          priceUpdatedAt          Data de Atualização do Preço   object
37                isOnSale                          Está à venda   object
38               floorplan                        Foto da planta   object
39                 details                              Detalhes   object

In [5]:
df_info.to_csv("MetaDado-DataSet.csv", sep=";")