In [12]:
import glob
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import csv

In [13]:
path0 = 'D:/cancer de pele/results/'

In [14]:
dataf = pd.read_csv(path0+'1/cancer-acc1.csv')
dataf.drop('Unnamed: 0', axis = 1, inplace = True)

In [15]:
dataf.head(10)

,0,1,2,3,4,5,6,7,8,9
0,0.761239,0.769231,0.788212,0.797203,0.804196,0.803197,0.806194,0.812188,0.824176,0.822178
1,0.737263,0.753247,0.779221,0.779221,0.778222,0.796204,0.818182,0.806194,0.822178,0.824176
2,0.746254,0.743257,0.752248,0.758242,0.777223,0.791209,0.807193,0.794206,0.797203,0.804196
3,0.740260,0.749251,0.771229,0.781219,0.778222,0.782218,0.812188,0.805195,0.807193,0.829171
4,0.729271,0.755245,0.754246,0.775225,0.765235,0.788212,0.801199,0.798202,0.800200,0.824176
5,0.762238,0.774226,0.776224,0.795205,0.803197,0.807193,0.800200,0.805195,0.824176,0.821179
6,0.738262,0.750250,0.762238,0.780220,0.783217,0.791209,0.793207,0.798202,0.822178,0.812188
7,0.715285,0.717283,0.745255,0.750250,0.755245,0.776224,0.788212,0.788212,0.799201,0.790210
8,0.738262,0.748252,0.786214,0.783217,0.787213,0.785215,0.791209,0.785215,0.791209,0.813187

In [16]:
x = dataf.iloc[7:8].values.tolist()

In [17]:
x[0]

[0.7152847051620483,
 0.7172827124595642,
 0.7452547550201416,
 0.7502497434616089,
 0.7552447319030762,
 0.7762237787246704,
 0.7882117629051208,
 0.7882117629051208,
 0.7992007732391357,
 0.7902097702026367]

In [18]:
list = []
for i in range(9):
    for j in range(10):
        x = dataf.iloc[i:i+1].values.tolist()
        inp = [i+1,1001, j+1 ,2**6,x[0][j]]
        list.append(inp)

In [19]:
print(list)

[[1, 1001, 1, 64, 0.7612387537956238], [1, 1001, 2, 64, 0.7692307829856873], [1, 1001, 3, 64, 0.7882117629051208], [1, 1001, 4, 64, 0.7972028255462646], [1, 1001, 5, 64, 0.8041958212852478], [1, 1001, 6, 64, 0.8031967878341675], [1, 1001, 7, 64, 0.8061938285827637], [1, 1001, 8, 64, 0.8121877908706665], [1, 1001, 9, 64, 0.8241758346557617], [1, 1001, 10, 64, 0.8221778273582458], [2, 1001, 1, 64, 0.7372627258300781], [2, 1001, 2, 64, 0.7532467246055603], [2, 1001, 3, 64, 0.7792207598686218], [2, 1001, 4, 64, 0.7792207598686218], [2, 1001, 5, 64, 0.7782217860221863], [2, 1001, 6, 64, 0.7962037920951843], [2, 1001, 7, 64, 0.8181818127632141], [2, 1001, 8, 64, 0.8061938285827637], [2, 1001, 9, 64, 0.8221778273582458], [2, 1001, 10, 64, 0.8241758346557617], [3, 1001, 1, 64, 0.7462537288665771], [3, 1001, 2, 64, 0.7432567477226257], [3, 1001, 3, 64, 0.7522477507591248], [3, 1001, 4, 64, 0.7582417726516724], [3, 1001, 5, 64, 0.777222752571106], [3, 1001, 6, 64, 0.791208803653717], [3, 1001, 7, 64, 0.8071928024291992], [3, 1001, 8, 64, 0.7942057847976685], [3, 1001, 9, 64, 0.7972028255462646], [3, 1001, 10, 64, 0.8041958212852478], [4, 1001, 1, 64, 0.7402597665786743], [4, 1001, 2, 64, 0.7492507696151733], [4, 1001, 3, 64, 0.7712287902832031], [4, 1001, 4, 64, 0.7812187671661377], [4, 1001, 5, 64, 0.7782217860221863], [4, 1001, 6, 64, 0.782217800617218], [4, 1001, 7, 64, 0.8121877908706665], [4, 1001, 8, 64, 0.8051947951316833], [4, 1001, 9, 64, 0.8071928024291992], [4, 1001, 10, 64, 0.829170823097229], [5, 1001, 1, 64, 0.7292707562446594], [5, 1001, 2, 64, 0.7552447319030762], [5, 1001, 3, 64, 0.7542457580566406], [5, 1001, 4, 64, 0.7752248048782349], [5, 1001, 5, 64, 0.7652347683906555], [5, 1001, 6, 64, 0.7882117629051208], [5, 1001, 7, 64, 0.8011987805366516], [5, 1001, 8, 64, 0.7982017993927002], [5, 1001, 9, 64, 0.8001998066902161], [5, 1001, 10, 64, 0.8241758346557617], [6, 1001, 1, 64, 0.7622377872467041], [6, 1001, 2, 64, 0.7742257714271545], [6, 1001, 3, 64, 0.7762237787246704], [6, 1001, 4, 64, 0.7952048182487488], [6, 1001, 5, 64, 0.8031967878341675], [6, 1001, 6, 64, 0.8071928024291992], [6, 1001, 7, 64, 0.8001998066902161], [6, 1001, 8, 64, 0.8051947951316833], [6, 1001, 9, 64, 0.8241758346557617], [6, 1001, 10, 64, 0.8211787939071655], [7, 1001, 1, 64, 0.7382617592811584], [7, 1001, 2, 64, 0.7502497434616089], [7, 1001, 3, 64, 0.7622377872467041], [7, 1001, 4, 64, 0.7802197933197021], [7, 1001, 5, 64, 0.7832167744636536], [7, 1001, 6, 64, 0.791208803653717], [7, 1001, 7, 64, 0.7932068109512329], [7, 1001, 8, 64, 0.7982017993927002], [7, 1001, 9, 64, 0.8221778273582458], [7, 1001, 10, 64, 0.8121877908706665], [8, 1001, 1, 64, 0.7152847051620483], [8, 1001, 2, 64, 0.7172827124595642], [8, 1001, 3, 64, 0.7452547550201416], [8, 1001, 4, 64, 0.7502497434616089], [8, 1001, 5, 64, 0.7552447319030762], [8, 1001, 6, 64, 0.7762237787246704], [8, 1001, 7, 64, 0.7882117629051208], [8, 1001, 8, 64, 0.7882117629051208], [8, 1001, 9, 64, 0.7992007732391357], [8, 1001, 10, 64, 0.7902097702026367], [9, 1001, 1, 64, 0.7382617592811584], [9, 1001, 2, 64, 0.748251736164093], [9, 1001, 3, 64, 0.7862138152122498], [9, 1001, 4, 64, 0.7832167744636536], [9, 1001, 5, 64, 0.7872127890586853], [9, 1001, 6, 64, 0.7852147817611694], [9, 1001, 7, 64, 0.791208803653717], [9, 1001, 8, 64, 0.7852147817611694], [9, 1001, 9, 64, 0.791208803653717], [9, 1001, 10, 64, 0.8131868243217468]]

In [20]:
colLabels = ['id pack','size', 'epocas', 'batch', 'acurácia']
print(colLabels)

['id pack', 'size', 'epocas', 'batch', 'acurácia']

In [21]:
dat = pd.DataFrame(list, columns=colLabels)

In [22]:
dat.to_csv('C:/Users/MADEIRA/Pictures/DATA CANCER/acuracias.csv')